"use client";
import Link from "next/link";
import { ArrowRight, Bell, Check, ChevronRight, CreditCard, FileCheck2, Plane, ShieldCheck, Star, Wallet } from "lucide-react";
import { useState } from "react";
import { demoUser } from "@/data/user";
import { useDemo } from "./demo-provider";

export function Dashboard(){const {demo,wallet,miles,alerts,reservations}=useDemo();const [kyc,setKyc]=useState(0);if(!demo&&kyc<3)return <div className="container-blajet py-16"><div className="mx-auto max-w-xl raised p-7 sm:p-10"><p className="eyebrow">Acceso BlaJet · Paso {kyc+1} de 3</p><h1 className="display mt-5 text-5xl">{kyc===0?"Empecemos por ti.":kyc===1?"Verifica tu identidad.":"Una última comprobación."}</h1><p className="mt-5 text-sm leading-7 text-muted">{kyc===0?"Crea tu perfil para recibir cotizaciones y reservar con operadores verificados.":kyc===1?"Sube una imagen de tu pasaporte. En esta demo no se almacena ningún archivo real.":"La selfie confirma que el documento te pertenece. Simularemos la validación de forma segura."}</p><div className="mt-7 border border-dashed hairline p-8 text-center"><FileCheck2 className="mx-auto text-champagne"/><p className="mt-3 text-xs text-muted">{kyc===0?"Nombre · email · teléfono":kyc===1?"Pasaporte o documento nacional":"Selfie de verificación"}</p></div><button onClick={()=>setKyc(v=>v+1)} className="btn-primary mt-6 w-full">{kyc===2?"Completar verificación":"Continuar"}<ArrowRight size={14}/></button></div></div>;
  return <div className="container-blajet py-10 sm:py-16"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Modo demo · Usuario precargado</p><h1 className="display mt-4 text-5xl">Buenos días, Carlos.</h1><p className="mt-4 text-sm text-muted">Miembro BlaJet Black · KYC verificado <ShieldCheck size={14} className="inline text-success"/></p></div><Link href="/investors" className="btn-secondary">Vista inversores <ArrowRight size={14}/></Link></div>
    <div className="mt-9 grid gap-px overflow-hidden border hairline bg-line sm:grid-cols-3"><div className="bg-raised p-6"><Wallet size={18} className="text-champagne"/><p className="mt-5 text-4xl font-semibold tabular">{wallet.toLocaleString("es-ES")} <small className="text-xs font-normal text-muted">EUR</small></p><p className="mt-2 text-xs text-muted">Saldo disponible en wallet</p></div><div className="bg-raised p-6"><Star size={18} className="text-champagne"/><p className="mt-5 text-4xl font-semibold tabular">{miles.toLocaleString("es-ES")}</p><p className="mt-2 text-xs text-muted">BlaJet Miles · nivel Black</p></div><div className="bg-raised p-6"><Bell size={18} className="text-champagne"/><p className="mt-5 text-4xl font-semibold tabular">{alerts.length}</p><p className="mt-2 text-xs text-muted">Alertas activas</p></div></div>
    <div className="mt-10 grid gap-8 lg:grid-cols-[1.35fr_.65fr]"><div><section><div className="flex items-center justify-between"><p className="eyebrow">Próximos vuelos</p><Link href="/pools" className="text-xs text-champagne">Explorar <ChevronRight size={13} className="inline"/></Link></div><div className="raised mt-4 p-6"><span className="border border-success px-2 py-1 text-[9px] uppercase tracking-wider text-success">Pool activo</span><div className="mt-6 flex items-center justify-between"><div><p className="text-2xl font-semibold">MAD → IBZ</p><p className="mt-2 text-xs text-muted">23 AGO · 17:30 · Phenom 300E</p></div><Plane className="text-champagne" strokeWidth={1.3}/></div><div className="mt-6 h-1 bg-line"><div className="h-full w-[62.5%] bg-champagne"/></div><p className="mt-2 text-[10px] text-muted">5/8 viajeros · precio actual 1.520 €/plaza</p></div>{reservations.map((r,i)=><div key={i} className="mt-3 border border-success p-4 text-sm text-success"><Check size={14} className="mr-2 inline"/>Nueva reserva: {r}</div>)}</section>
      <section className="mt-10"><p className="eyebrow">Historial</p><div className="mt-4 divide-y hairline border-y hairline">{demoUser.pastBookings.map(b=><div key={b.route+b.date} className="grid grid-cols-[1fr_auto] gap-4 py-5"><div><p className="font-semibold">{b.route}</p><p className="mt-1 text-xs text-muted">{b.date} · {b.aircraft}</p></div><span className="tabular text-sm">{b.amount.toLocaleString("es-ES")} €</span></div>)}</div></section></div>
      <aside><section className="raised p-6"><p className="eyebrow">BlaJet Black</p><h2 className="font-serif mt-5 text-3xl">Tu concierge, siempre a bordo.</h2><p className="mt-4 text-xs leading-6 text-muted">Acceso anticipado a empty legs, comisión reducida y asistencia 24/7.</p><button className="btn-primary mt-6 w-full">Hablar con concierge</button></section><section className="mt-5 border hairline p-6"><p className="eyebrow">Alertas guardadas</p><div className="mt-4 space-y-3">{alerts.map(a=><p key={a} className="flex items-center justify-between border-b hairline pb-3 text-sm"><span>{a}</span><span className="h-1.5 w-1.5 rounded-full bg-success"/></p>)}</div></section><section className="mt-5 border hairline p-6"><CreditCard size={18} className="text-champagne"/><p className="mt-4 text-sm font-semibold">Visa •••• 2841</p><p className="mt-1 text-xs text-muted">Método de pago principal</p></section></aside></div>
  </div>}
