"use client";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Bell, Filter, Info, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { emptyLegs } from "@/data/empty-legs";
import { operators } from "@/data/operators";
import { RouteVisual } from "./route-visual";
import { Countdown } from "./countdown";
import { useDemo } from "./demo-provider";

export function EmptyLegsList(){
  const [from,setFrom]=useState("TODOS"),[to,setTo]=useState("TODOS"),[type,setType]=useState("all"),[max,setMax]=useState(12000),[alertDone,setAlertDone]=useState(false); const {addAlert}=useDemo();
  const filtered=useMemo(()=>emptyLegs.filter(l=>(from==="TODOS"||l.from===from)&&(to==="TODOS"||l.to===to)&&(type==="all"||(type==="seat"&&l.seatEligible)||(type==="bid"&&l.bidEnabled))&&l.fullPrice<=max),[from,to,type,max]);
  const codes=["TODOS",...Array.from(new Set(emptyLegs.flatMap(l=>[l.from,l.to])))];
  return <><section className="border-b hairline bg-surface"><div className="container-blajet py-16 sm:py-20"><p className="eyebrow">Vuelos a precio de oportunidad</p><h1 className="display mt-5 max-w-4xl text-5xl sm:text-7xl">Un avión que vuelve vacío. Una ocasión que no se repite.</h1><p className="mt-6 max-w-xl text-sm leading-7 text-muted">Disponibilidad en tiempo real de operadores verificados. Reserva el jet completo o, donde la normativa lo permite, una sola plaza.</p></div></section>
    <section className="container-blajet py-10"><div className="raised grid gap-4 p-4 md:grid-cols-4"><label><span className="field-label">Origen</span><select className="field" value={from} onChange={e=>setFrom(e.target.value)}>{codes.map(c=><option key={c} value={c}>{c==="TODOS"?"Cualquier origen":c}</option>)}</select></label><label><span className="field-label">Destino</span><select className="field" value={to} onChange={e=>setTo(e.target.value)}>{codes.map(c=><option key={c} value={c}>{c==="TODOS"?"Cualquier destino":c}</option>)}</select></label><label><span className="field-label">Modalidad</span><select className="field" value={type} onChange={e=>setType(e.target.value)}><option value="all">Todas</option><option value="seat">Por plaza</option><option value="bid">Admite oferta</option></select></label><label><span className="field-label">Máximo vuelo completo · {max.toLocaleString("es-ES")} €</span><input type="range" min={4000} max={18000} step={500} value={max} onChange={e=>setMax(Number(e.target.value))} className="mt-3 w-full accent-[var(--champagne)]"/></label></div>
      <div className="mt-6 flex items-center justify-between"><p className="text-xs text-muted"><Filter size={13} className="mr-2 inline"/>{filtered.length} oportunidades</p><p className="hidden items-center gap-2 text-[10px] text-muted sm:flex"><span className="h-1.5 w-1.5 rounded-full bg-success"/> Datos actualizados hace 2 min</p></div>
      {filtered.length ? <div className="mt-6 grid gap-5 lg:grid-cols-2">{filtered.map(leg=>{const op=operators.find(o=>o.id===leg.operatorId)!;return <article key={leg.id} className="raised overflow-hidden"><Link href={`/empty-legs/${leg.id}`} className="group grid sm:grid-cols-[.85fr_1.15fr]"><div className="relative min-h-56 overflow-hidden"><Image src={leg.image} alt={leg.aircraft} fill sizes="(max-width:640px) 100vw, 35vw" className="object-cover transition-transform duration-700 group-hover:scale-[1.03]"/><div className="absolute left-3 top-3"><Countdown hours={leg.departureHours}/></div></div><div className="p-6"><RouteVisual from={leg.from} to={leg.to} compact/><p className="mt-4 text-xs text-muted">{leg.date} · {leg.time} · {leg.duration}</p><h2 className="mt-5 font-serif text-xl">{leg.aircraft}</h2><p className="mt-1 text-[11px] text-muted">{op.name} · {op.rating}/5</p><div className="mt-5 flex items-end justify-between border-t hairline pt-5"><div><p className="text-2xl font-semibold tabular">{leg.seatPrice.toLocaleString("es-ES")} <small className="text-xs font-normal text-muted">€/plaza</small></p><p className="mt-1 text-[10px] text-muted">Jet completo {leg.fullPrice.toLocaleString("es-ES")} €</p></div><ArrowRight size={18} className="text-champagne"/></div></div></Link><div className="flex flex-wrap gap-2 border-t hairline px-6 py-3">{leg.seatEligible&&<span className="flex items-center gap-1 border border-success px-2 py-1 text-[9px] uppercase tracking-wider text-success">Por plaza <Info size={10}/></span>}{leg.bidEnabled&&<span className="border border-champagne px-2 py-1 text-[9px] uppercase tracking-wider text-champagne">Admite oferta</span>}<span className="ml-auto text-[10px] text-success">Ahorras {(leg.charterPrice-leg.fullPrice).toLocaleString("es-ES")} €</span></div></article>})}</div> : <div className="raised mt-6 py-16 text-center"><Search className="mx-auto text-champagne" strokeWidth={1.3}/><h2 className="font-serif mt-5 text-3xl">No hay empty legs con esos filtros.</h2><p className="mx-auto mt-3 max-w-md text-sm text-muted">Las rutas cambian cada pocos minutos. Guarda una alerta y te avisaremos antes que nadie.</p><button onClick={()=>{addAlert(`${from} → ${to}`);setAlertDone(true)}} className="btn-primary mt-6"><Bell size={14}/>{alertDone?"Alerta creada":"Crear alerta"}</button></div>}
      <div className="mt-12 border border-champagne/50 p-6 sm:flex sm:items-center sm:justify-between"><div><p className="font-serif text-xl">¿Buscas una ruta concreta?</p><p className="mt-2 text-xs text-muted">Crea una alerta local. No necesitas dejar un teléfono durante la demo.</p></div><button onClick={()=>{addAlert("MAD → IBZ");setAlertDone(true)}} className="btn-secondary mt-5 sm:mt-0"><Bell size={14}/>{alertDone?"Alerta MAD–IBZ activa":"Avisarme de MAD–IBZ"}</button></div>
    </section></>;
}
