"use client";
import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, BadgeCheck, Check, Info, Leaf, Scale, ShieldCheck, X } from "lucide-react";
import { useState } from "react";
import type { EmptyLeg } from "@/data/empty-legs";
import type { Operator } from "@/data/operators";
import { RouteVisual } from "./route-visual";
import { Countdown } from "./countdown";
import { BookingModal } from "./booking-modal";

export function EmptyLegDetail({leg,operator}:{leg:EmptyLeg;operator:Operator}){
  const [mode,setMode]=useState<"seat"|"full">(leg.seatEligible?"seat":"full"),[seats,setSeats]=useState(1),[checkout,setCheckout]=useState(false),[bidOpen,setBidOpen]=useState(false),[bid,setBid]=useState(Math.round(leg.fullPrice*.82)),[bidResult,setBidResult]=useState<"accepted"|"rejected"|null>(null),[legal,setLegal]=useState(false);
  const price=mode==="seat"?leg.seatPrice*seats:leg.fullPrice;
  const submitBid=()=>{setBidResult(bid>=Math.round(leg.fullPrice*.9)?"accepted":"rejected")};
  return <div className="container-blajet py-8 sm:py-12"><Link href="/empty-legs" className="flex items-center gap-2 text-xs text-muted hover:text-champagne"><ArrowLeft size={14}/> Todas las oportunidades</Link>
    <div className="mt-7 grid gap-8 lg:grid-cols-[1.2fr_.8fr]"><div><div className="relative min-h-[330px] sm:min-h-[520px]"><Image src={leg.image} alt={leg.aircraft} fill priority sizes="(max-width:1024px) 100vw, 60vw" className="object-cover"/><div className="absolute left-4 top-4"><Countdown hours={leg.departureHours}/></div><div className="absolute bottom-4 left-4 bg-[#0A0B0F]/85 px-3 py-2 text-xs text-[#F2EFE8]">{leg.aircraft} · {operator.name}</div></div>
      <div className="mt-9"><p className="eyebrow">Empty leg · {leg.date}</p><div className="mt-5 max-w-2xl"><RouteVisual from={leg.from} to={leg.to}/></div><p className="mt-5 text-sm text-muted">Salida {leg.time} · {leg.duration} · {leg.seats} plazas disponibles</p></div>
      <div className="mt-10 grid gap-px bg-line sm:grid-cols-3"><div className="bg-canvas p-5"><ShieldCheck size={18} className="text-success"/><p className="mt-4 text-sm font-semibold">AOC verificado</p><p className="mt-1 text-xs text-muted">{operator.aoc}</p></div><div className="bg-canvas p-5"><Leaf size={18} className="text-success"/><p className="mt-4 text-sm font-semibold">0,72 t CO₂</p><p className="mt-1 text-xs text-muted">Compensación: 14 €</p></div><div className="bg-canvas p-5"><Scale size={18} className="text-champagne"/><p className="mt-4 text-sm font-semibold">Marco regulado</p><button onClick={()=>setLegal(true)} className="mt-1 text-left text-xs text-muted underline">Condiciones por plaza</button></div></div>
      <section className="mt-10"><p className="eyebrow">Operador</p><div className="mt-4 flex items-start gap-4 border-y hairline py-6"><span className="grid h-12 w-12 shrink-0 place-items-center border border-champagne font-serif text-champagne">{operator.name.split(" ").map(x=>x[0]).join("").slice(0,2)}</span><div><h2 className="font-serif text-2xl">{operator.name} <BadgeCheck size={17} className="inline text-success"/></h2><p className="mt-2 text-xs leading-5 text-muted">Base {operator.base} · {operator.fleetSize} aeronaves · {operator.rating}/5</p><p className="mt-3 text-xs leading-5 text-muted">{operator.emptyLegPolicy}</p></div></div></section>
    </div><aside className="raised h-fit p-6 lg:sticky lg:top-24"><p className="eyebrow">Elige cómo volar</p><div className="mt-5 grid grid-cols-2 gap-2"><button disabled={!leg.seatEligible} onClick={()=>setMode("seat")} className={`border p-3 text-xs ${mode==="seat"?"border-champagne text-champagne":"hairline text-muted"} disabled:opacity-30`}>Por plaza</button><button onClick={()=>setMode("full")} className={`border p-3 text-xs ${mode==="full"?"border-champagne text-champagne":"hairline text-muted"}`}>Jet completo</button></div>{mode==="seat"&&<label className="mt-5 block"><span className="field-label">Número de plazas</span><select value={seats} onChange={e=>setSeats(Number(e.target.value))} className="field">{Array.from({length:leg.seats},(_,i)=>i+1).map(n=><option key={n}>{n}</option>)}</select></label>}
      <div className="mt-6 border-y hairline py-5"><p className="text-xs text-muted">Precio actual</p><p className="mt-2 text-4xl font-semibold tabular">{price.toLocaleString("es-ES")} <small className="text-sm font-normal text-muted">EUR</small></p><div className="mt-5 h-1 bg-line"><div className="h-full bg-champagne" style={{width:`${Math.round(price/(mode==="full"?leg.charterPrice:leg.charterPrice)*100)}%`}}/></div><div className="mt-2 flex justify-between text-[10px] text-muted"><span>BlaJet</span><span>Charter {leg.charterPrice.toLocaleString("es-ES")} €</span></div><p className="mt-4 text-xs text-success">Ahorro frente a charter: {(leg.charterPrice-price).toLocaleString("es-ES")} €</p></div>
      <div className="mt-5 space-y-2 text-xs text-muted"><p className="flex gap-2"><Check size={14} className="text-success"/>Tasas y handling incluidos</p><p className="flex gap-2"><Check size={14} className="text-success"/>Confirmación inmediata</p><p className="flex gap-2"><Check size={14} className="text-success"/>Protección BlaJet</p></div><button onClick={()=>setCheckout(true)} className="btn-primary mt-7 w-full">Reservar {mode==="seat"?seats===1?"plaza":`${seats} plazas`:"jet completo"}</button>{leg.bidEnabled&&<button onClick={()=>setBidOpen(true)} className="btn-secondary mt-3 w-full">Hacer una oferta</button>}</aside></div>
    <BookingModal open={checkout} onClose={()=>setCheckout(false)} title={`${leg.from} → ${leg.to} · ${mode==="seat"?`${seats} plaza${seats>1?"s":""}`:"jet completo"}`} price={price}/>
    {bidOpen&&<div className="fixed inset-0 z-[80] grid place-items-end bg-black/65 sm:place-items-center sm:p-6"><div className="raised w-full max-w-md p-6 sm:p-8"><div className="flex justify-between"><span className="eyebrow">Oferta experimental</span><button onClick={()=>setBidOpen(false)} aria-label="Cerrar"><X size={18}/></button></div><h2 className="display mt-5 text-4xl">Propón tu precio.</h2><p className="mt-4 text-sm leading-6 text-muted">{operator.name} responderá al instante en esta simulación. Publicado: {leg.fullPrice.toLocaleString("es-ES")} €.</p>{!bidResult?<><label className="mt-6 block"><span className="field-label">Tu oferta por el jet completo</span><input className="field tabular" type="number" min={1000} max={leg.fullPrice} value={bid} onChange={e=>setBid(Number(e.target.value))}/></label><button onClick={submitBid} className="btn-primary mt-5 w-full">Enviar oferta de {bid.toLocaleString("es-ES")} €</button></>:bidResult==="accepted"?<div className="mt-6 border border-success p-5"><p className="font-semibold text-success">Oferta aceptada</p><p className="mt-2 text-xs leading-5 text-muted">El operador ha bloqueado el avión durante 10 minutos.</p><button onClick={()=>{setBidOpen(false);setCheckout(true)}} className="btn-primary mt-5 w-full">Completar reserva</button></div>:<div className="mt-6 border border-alert p-5"><p className="font-semibold text-alert">El operador no puede aceptar este importe</p><p className="mt-2 text-xs leading-5 text-muted">El mínimo operativo para este trayecto es {Math.round(leg.fullPrice*.9).toLocaleString("es-ES")} €. Puedes ajustar tu propuesta o reservar al precio publicado.</p><button onClick={()=>{setBid(Math.round(leg.fullPrice*.9));setBidResult(null)}} className="btn-secondary mt-5 w-full">Ajustar al mínimo</button></div>}</div></div>}
    {legal&&<div className="fixed inset-0 z-[80] grid place-items-center bg-black/65 p-6"><div className="raised max-w-md p-7"><div className="flex justify-between"><span className="eyebrow">Venta por plaza</span><button onClick={()=>setLegal(false)}><X size={18}/></button></div><p className="mt-5 text-sm leading-7 text-muted">La venta por asiento se ofrece únicamente en rutas y jurisdicciones donde el marco regulatorio lo permite. Cada pasajero debe completar verificación de identidad, pasaporte y selfie antes de la salida.</p><button onClick={()=>setLegal(false)} className="btn-primary mt-6">Entendido</button></div></div>}
  </div>;
}
