"use client";
import { Activity, ArrowUpRight, Clock3, Plane, Users } from "lucide-react";
import { AnimatedNumber } from "./animated-number";
import { funnel, monthlyGmv } from "@/data/investors";

export function InvestorsDashboard(){const max=Math.max(...monthlyGmv.map(d=>d.charter+d.empty+d.pool));const last=monthlyGmv.at(-1)!;const total=last.charter+last.empty+last.pool;return <div className="container-blajet py-10 sm:py-16"><div className="flex flex-col justify-between gap-5 border-b hairline pb-8 sm:flex-row sm:items-end"><div><p className="eyebrow">Confidencial · Demo de modelo</p><h1 className="display mt-4 text-5xl sm:text-6xl">BlaJet en números.</h1></div><p className="max-w-sm text-xs leading-5 text-muted">Datos ilustrativos — proyección de modelo. Importes expresados en miles de euros salvo indicación.</p></div>
  <div className="mt-8 grid gap-px overflow-hidden border hairline bg-line sm:grid-cols-2 lg:grid-cols-4">{[[total,"GMV agosto · k€",ArrowUpRight],[42,"Operadores activos",Plane],[68,"Pools completados · %",Users],[4,"Primera oferta · min",Clock3]].map(([v,l,Icon])=>{const I=Icon as typeof Plane;return <div key={String(l)} className="bg-raised p-6"><I size={18} className="text-champagne"/><p className="mt-5 text-4xl font-semibold"><AnimatedNumber value={v as number}/>{String(l).includes("%")&&"%"}</p><p className="mt-2 text-xs text-muted">{l as string}</p></div>})}</div>
  <section className="mt-8 raised p-6 sm:p-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><p className="eyebrow">GMV mensual por modalidad</p><h2 className="font-serif mt-3 text-3xl">Crecimiento compuesto del marketplace</h2></div><div className="flex gap-4 text-[10px] text-muted"><span><i className="mr-1 inline-block h-2 w-2 bg-champagne"/>Charter</span><span><i className="mr-1 inline-block h-2 w-2 bg-muted"/>Empty legs</span><span><i className="mr-1 inline-block h-2 w-2 border border-champagne"/>Pooling</span></div></div><div className="mt-9 flex h-72 items-end gap-2 border-b hairline sm:gap-4">{monthlyGmv.map(d=>{const h=(d.charter+d.empty+d.pool)/max*100;return <div key={d.m} className="group flex h-full flex-1 flex-col justify-end"><div className="relative w-full bg-champagne transition-opacity group-hover:opacity-80" style={{height:`${h}%`}}><div className="absolute inset-x-0 bottom-0 bg-muted/50" style={{height:`${(d.empty+d.pool)/(d.charter+d.empty+d.pool)*100}%`}}/><div className="absolute inset-x-0 bottom-0 border border-champagne bg-canvas/50" style={{height:`${d.pool/(d.charter+d.empty+d.pool)*100}%`}}/><span className="absolute -top-6 left-1/2 hidden -translate-x-1/2 text-[9px] tabular group-hover:block">{d.charter+d.empty+d.pool}</span></div><span className="mt-3 text-center text-[8px] text-muted sm:text-[10px]">{d.m}</span></div>})}</div></section>
  <div className="mt-8 grid gap-8 lg:grid-cols-2"><section className="raised p-6 sm:p-8"><p className="eyebrow">Funnel de conversión</p><div className="mt-7 space-y-5">{funnel.map(([label,value],i)=><div key={label}><div className="flex justify-between text-xs"><span>{label}</span><span className="tabular text-muted">{value.toLocaleString("es-ES")} · {Math.round(value/funnel[0][1]*100)}%</span></div><div className="mt-2 h-1.5 bg-line"><div className="h-full bg-champagne" style={{width:`${value/funnel[0][1]*100}%`}}/></div>{i<funnel.length-1&&<p className="mt-1 text-[9px] text-muted">{Math.round(funnel[i+1][1]/value*100)}% avanza</p>}</div>)}</div></section><section className="raised p-6 sm:p-8"><p className="eyebrow">Take rate y revenue mensual</p><div className="mt-7 divide-y hairline">{[["Charter",384,8],["Empty legs",142,12],["Pooling",96,15]].map(([label,gmv,rate])=><div key={String(label)} className="grid grid-cols-3 py-5 text-sm"><span>{label}</span><span className="text-center tabular text-muted">{rate}%</span><span className="text-right tabular">{Math.round(Number(gmv)*Number(rate)/100)} k€</span></div>)}</div><div className="mt-6 flex justify-between border-t border-champagne pt-5"><span className="text-sm font-semibold">Revenue agosto</span><span className="text-2xl font-semibold tabular">75 k€</span></div></section></div>
  <div className="mt-8 grid gap-px overflow-hidden border hairline bg-line md:grid-cols-3"><section className="bg-raised p-6"><p className="eyebrow">Unit economics</p><p className="mt-5 text-3xl font-semibold tabular">4,7×</p><p className="mt-1 text-xs text-muted">LTV / CAC blended</p><div className="mt-5 space-y-2 text-xs"><p className="flex justify-between"><span className="text-muted">CAC premium</span><span>184 €</span></p><p className="flex justify-between"><span className="text-muted">LTV premium</span><span>1.120 €</span></p><p className="flex justify-between"><span className="text-muted">CAC aspiracional</span><span>48 €</span></p></div></section><section className="bg-raised p-6"><p className="eyebrow">Ticket medio</p><div className="mt-5 space-y-4">{[["Charter","9.840 €"],["Empty leg","2.460 €"],["Pooling","1.340 €"]].map(([a,b])=><p key={a} className="flex justify-between border-b hairline pb-3 text-sm"><span className="text-muted">{a}</span><span className="tabular">{b}</span></p>)}</div></section><section className="bg-raised p-6"><p className="eyebrow">Marketplace</p><div className="mt-5 space-y-4"><p><span className="text-3xl font-semibold tabular">186</span><span className="ml-2 text-xs text-muted">empty legs / mes</span></p><p><span className="text-3xl font-semibold tabular">68%</span><span className="ml-2 text-xs text-muted">pools completos</span></p><p><span className="text-3xl font-semibold tabular">4,2</span><span className="ml-2 text-xs text-muted">min primera oferta</span></p></div></section></div>
  <p className="mt-8 flex items-center gap-2 text-[10px] text-muted"><Activity size={12}/> Dataset coherente con los tres operadores y precios mostrados en la demo de producto.</p></div>}
