"use client";
import Link from "next/link";
import { ArrowRight, BadgeCheck, Plus, Search, Users, X } from "lucide-react";
import { useMemo, useState } from "react";
import { pools } from "@/data/pools";
import { RouteVisual } from "./route-visual";

export function PoolsList(){
  const [kind,setKind]=useState("all"),[query,setQuery]=useState(""),[create,setCreate]=useState(false),[created,setCreated]=useState(false);
  const visible=useMemo(()=>pools.filter(p=>(kind==="all"||p.kind===kind)&&(`${p.from} ${p.to}`.toLowerCase().includes(query.toLowerCase()))),[kind,query]);
  return <><section className="border-b hairline"><div className="container-blajet grid gap-10 py-16 sm:py-20 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><div><p className="eyebrow">Comparte jet, comparte gastos</p><h1 className="display mt-5 text-5xl sm:text-7xl">El precio baja. La experiencia no.</h1></div><div><p className="max-w-lg text-sm leading-7 text-muted">Únete a una ruta propuesta o a las plazas libres de un vuelo ya confirmado. Perfiles verificados, reglas claras y coste visible para todos.</p><button onClick={()=>setCreate(true)} className="btn-primary mt-6"><Plus size={15}/> Crear un pool</button></div></div></section>
    <section className="container-blajet py-10"><div className="flex flex-col gap-4 border-b hairline pb-6 sm:flex-row sm:items-end sm:justify-between"><label className="w-full max-w-sm"><span className="field-label">Buscar ruta</span><span className="relative block"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted"/><input value={query} onChange={e=>setQuery(e.target.value)} className="field pl-9" placeholder="MAD, IBZ, GVA…"/></span></label><div className="flex gap-2"><button onClick={()=>setKind("all")} className={kind==="all"?"btn-primary":"btn-secondary"}>Todos</button><button onClick={()=>setKind("charter")} className={kind==="charter"?"btn-primary":"btn-secondary"}>Por confirmar</button><button onClick={()=>setKind("owner")} className={kind==="owner"?"btn-primary":"btn-secondary"}>Ya confirmados</button></div></div>
      {visible.length?<div className="mt-7 grid gap-5 lg:grid-cols-3">{visible.map(pool=>{const price=Math.round(pool.total/pool.joined);const full=Math.round(pool.total/1);return <Link href={`/pools/${pool.id}`} key={pool.id} className="group raised p-6 hover:border-champagne"><div className="flex items-center justify-between"><span className={`border px-2 py-1 text-[9px] uppercase tracking-wider ${pool.kind==="owner"?"border-success text-success":"border-champagne text-champagne"}`}>{pool.kind==="owner"?"Vuelo confirmado":"Pool abierto"}</span><span className="text-[10px] text-muted">{pool.date}</span></div><div className="mt-7"><RouteVisual from={pool.from} to={pool.to} compact/></div><p className="mt-5 text-xs text-muted">{pool.aircraft}</p><div className="mt-7 flex items-center justify-between border-y hairline py-5"><div><span className="text-3xl font-semibold tabular">{price.toLocaleString("es-ES")}</span> <small className="text-muted">€/plaza</small><p className="mt-1 text-[10px] text-success">Hasta −{Math.round((1-price/full)*100)}% al compartir</p></div><ArrowRight size={18} className="text-champagne transition-transform group-hover:translate-x-1"/></div><div className="mt-5"><div className="flex justify-between text-[10px] text-muted"><span>{pool.joined}/{pool.capacity} plazas</span><span>{pool.kind==="owner"?"Confirmado":`Confirma en ${pool.confirmAt}`}</span></div><div className="mt-2 h-1 bg-line"><div className="h-full bg-champagne" style={{width:`${pool.joined/pool.capacity*100}%`}}/></div></div><p className="mt-5 flex items-center gap-2 text-xs"><span className="grid h-7 w-7 place-items-center rounded-full bg-surface text-[9px]">{pool.members[0]}</span>{pool.host}{pool.verified&&<BadgeCheck size={14} className="text-success"/>}<span className="ml-auto text-muted">{pool.rating}/5</span></p></Link>})}</div>:<div className="raised mt-7 py-16 text-center"><Users className="mx-auto text-champagne"/><h2 className="font-serif mt-5 text-3xl">Aún no hay pools en esa ruta.</h2><p className="mt-3 text-sm text-muted">Sé el primero en proponerla y deja que otros viajeros se sumen.</p><button onClick={()=>setCreate(true)} className="btn-primary mt-6"><Plus size={14}/> Crear esta ruta</button></div>}
      <p className="mt-10 border-l-2 border-champagne pl-4 text-xs leading-5 text-muted">El pooling se ofrece bajo la modalidad de compartición de gastos conforme a la normativa aplicable en cada jurisdicción.</p>
    </section>
    {create&&<div className="fixed inset-0 z-[80] grid place-items-end bg-black/65 sm:place-items-center sm:p-6"><div className="raised max-h-[94vh] w-full max-w-xl overflow-y-auto p-6 sm:p-8"><div className="flex justify-between"><span className="eyebrow">Nuevo pool</span><button onClick={()=>setCreate(false)}><X size={18}/></button></div>{created?<div className="py-10 text-center"><span className="mx-auto grid h-12 w-12 place-items-center border border-success text-success">✓</span><h2 className="display mt-6 text-4xl">Ruta publicada.</h2><p className="mt-3 text-sm text-muted">Avisaremos a viajeros con alertas compatibles y a operadores de la red.</p><button onClick={()=>setCreate(false)} className="btn-primary mt-6">Ver mis pools</button></div>:<><h2 className="display mt-5 text-4xl">Propón una ruta.</h2><div className="mt-7 grid gap-4 sm:grid-cols-2"><label><span className="field-label">Origen</span><select className="field"><option>MAD · Madrid</option><option>BCN · Barcelona</option><option>GVA · Ginebra</option></select></label><label><span className="field-label">Destino</span><select className="field"><option>IBZ · Ibiza</option><option>PMI · Palma</option><option>NCE · Niza</option></select></label><label><span className="field-label">Fecha</span><input type="date" defaultValue="2026-09-12" className="field"/></label><label><span className="field-label">Categoría</span><select className="field"><option>Light jet · 8 plazas</option><option>Midsize · 9 plazas</option></select></label></div><div className="mt-6 border-y hairline py-5"><p className="text-xs text-muted">Estimación total</p><p className="mt-2 text-3xl font-semibold tabular">8.200 <small className="text-xs font-normal text-muted">EUR</small></p><p className="mt-2 text-xs text-success">Desde 1.025 €/plaza con 8 viajeros</p></div><button onClick={()=>setCreated(true)} className="btn-primary mt-6 w-full">Publicar pool</button></>}</div></div>}
  </>;
}
