"use client";
import { BadgeCheck, Check, MessageCircle, ShieldCheck, Sparkles, Users } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import type { Pool } from "@/data/pools";
import { AnimatedNumber } from "./animated-number";
import { RouteVisual } from "./route-visual";
import { BookingModal } from "./booking-modal";

export function PoolDetail({pool}:{pool:Pool}){
  const [joined,setJoined]=useState(pool.joined),[pulse,setPulse]=useState(false),[checkout,setCheckout]=useState(false),[autoJoined,setAutoJoined]=useState(false),[chat,setChat]=useState(false); const fired=useRef(false);
  const price=Math.round(pool.total/joined),previous=Math.round(pool.total/Math.max(1,joined-1));
  useEffect(()=>{const timer=setTimeout(()=>{if(!fired.current){fired.current=true;setJoined(v=>Math.min(pool.capacity,v+1));setPulse(true);setAutoJoined(true);setTimeout(()=>setPulse(false),1300)}},2600);return()=>clearTimeout(timer)},[pool.capacity]);
  const join=()=>{setJoined(v=>Math.min(pool.capacity,v+1));setPulse(true);setTimeout(()=>setPulse(false),1300);setCheckout(true)};
  return <div className="container-blajet py-10 sm:py-16"><div className="grid gap-10 lg:grid-cols-[1.15fr_.85fr]"><div><div className="flex flex-wrap items-center gap-3"><span className={`border px-2 py-1 text-[9px] uppercase tracking-wider ${pool.kind==="owner"?"border-success text-success":"border-champagne text-champagne"}`}>{pool.kind==="owner"?"Vuelo confirmado":"Confirma con el grupo"}</span>{autoJoined&&<span className="animate-rise text-xs text-success">Marina se acaba de unir · el precio ha bajado</span>}</div><p className="eyebrow mt-8">{pool.date}</p><div className="mt-5 max-w-2xl"><RouteVisual from={pool.from} to={pool.to}/></div><p className="mt-5 text-sm text-muted">{pool.aircraft} · {pool.capacity} plazas · Salida privada</p>
      <section className={`raised mt-9 p-6 sm:p-8 ${pulse?"animate-pulse-soft border-champagne":""}`}><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="eyebrow">Precio actual por persona</p><p className="mt-3 text-5xl font-semibold"><AnimatedNumber value={price}/> <small className="text-sm font-normal text-muted">EUR</small></p>{joined>pool.joined&&<p className="mt-2 text-xs text-success">Antes <span className="line-through">{previous.toLocaleString("es-ES")} €</span> · ahorras {(previous-price).toLocaleString("es-ES")} €</p>}</div><div className="text-sm"><strong className="tabular">{joined}/{pool.capacity}</strong> <span className="text-muted">plazas ocupadas</span></div></div><div className="mt-7 h-2 bg-line"><div className="h-full bg-champagne transition-all duration-700" style={{width:`${joined/pool.capacity*100}%`}}/></div><div className="mt-3 flex justify-between text-[10px] text-muted"><span>Inicio</span><span>{pool.kind==="owner"?"Vuelo confirmado":`Confirmación en ${pool.confirmAt} viajeros`}</span><span>Completo</span></div></section>
      <section className="mt-10"><p className="eyebrow">Tu anfitrión y el grupo</p><div className="mt-5 flex items-center border-y hairline py-6"><span className="grid h-12 w-12 place-items-center rounded-full bg-surface font-semibold">{pool.members[0]}</span><div className="ml-4"><p className="font-serif text-xl">{pool.host} <BadgeCheck size={15} className="inline text-success"/></p><p className="mt-1 text-xs text-muted">Identidad verificada · {pool.rating}/5 · 6 vuelos compartidos</p></div><button onClick={()=>setChat(!chat)} className="btn-secondary ml-auto"><MessageCircle size={14}/><span className="hidden sm:inline">Chat</span></button></div>{chat&&<div className="surface animate-rise mt-3 p-5 text-sm"><p className="max-w-[82%] bg-raised p-3 text-xs leading-5">Hola, Carlos. Salimos puntuales; he pedido al operador espacio extra para equipaje.</p><p className="mt-3 ml-auto max-w-[82%] border border-champagne p-3 text-xs leading-5">Perfecto, gracias. Nos vemos en la terminal ejecutiva.</p><input className="field mt-4" placeholder="Escribe al grupo…"/></div>}<div className="mt-6 flex -space-x-2">{Array.from({length:joined},(_,i)=><span key={i} className="grid h-9 w-9 place-items-center rounded-full border-2 border-canvas bg-raised text-[10px] font-semibold">{pool.members[i]||["MC","JD","LV","AG"][i%4]}</span>)}{Array.from({length:Math.max(0,pool.capacity-joined)},(_,i)=><span key={`e${i}`} className="grid h-9 w-9 place-items-center rounded-full border-2 border-canvas bg-surface text-xs text-muted">+</span>)}</div></section>
      <section className="mt-10 grid gap-px bg-line sm:grid-cols-2"><div className="bg-canvas p-6"><ShieldCheck className="text-success" size={18}/><h2 className="font-serif mt-4 text-xl">Reglas del pool</h2><div className="mt-4 space-y-2">{pool.rules.map(r=><p key={r} className="flex gap-2 text-xs leading-5 text-muted"><Check size={13} className="mt-1 shrink-0 text-success"/>{r}</p>)}</div></div><div className="bg-canvas p-6"><Sparkles className="text-champagne" size={18}/><h2 className="font-serif mt-4 text-xl">Cancelación</h2><p className="mt-4 text-xs leading-5 text-muted">Reembolso íntegro mientras el pool no esté confirmado. Después, crédito BlaJet si encontramos un reemplazo para tu plaza.</p></div></section>
    </div><aside className={`raised h-fit p-6 lg:sticky lg:top-24 ${pulse?"animate-pulse-soft border-champagne":""}`}><Users size={20} className="text-champagne"/><h2 className="font-serif mt-5 text-3xl">Únete a este vuelo.</h2><p className="mt-4 text-sm leading-6 text-muted">Tu plaza queda protegida. El importe final solo puede bajar si se unen más viajeros.</p><div className="mt-6 border-y hairline py-5"><div className="flex items-end justify-between"><span className="text-xs text-muted">Precio máximo</span><span className="text-3xl font-semibold tabular">{price.toLocaleString("es-ES")} <small className="text-xs font-normal text-muted">EUR</small></span></div><p className="mt-3 text-xs text-success">Puede bajar hasta {Math.round(pool.total/pool.capacity).toLocaleString("es-ES")} €</p></div><button onClick={join} disabled={joined>=pool.capacity} className="btn-primary mt-6 w-full disabled:opacity-40">{joined>=pool.capacity?"Pool completo":"Unirme al pool"}</button><p className="mt-4 text-[10px] leading-4 text-muted">Compartición de gastos conforme a la normativa aplicable. Todos los viajeros completan KYC antes de la salida.</p></aside></div><BookingModal open={checkout} onClose={()=>setCheckout(false)} title={`${pool.from} → ${pool.to} · Plaza en pool`} price={price}/></div>;
}
