"use client";

import Image from "next/image";
import { ArrowLeft, ArrowRight, Check, Clock3, Luggage, PawPrint, Plane, ShieldCheck, Sparkles, Wifi } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { aircraftImage, airports, cabinImage, jetCategories } from "@/data/aviation";
import { operators } from "@/data/operators";
import { BookingModal } from "./booking-modal";
import { RouteVisual } from "./route-visual";

type Stage = "form" | "waiting" | "offers" | "detail";
type Form = { from: string; to: string; date: string; time: string; trip: "one"|"return"; passengers: number; category: string; extras: string[] };
const offers = [
  { id: "senda", operatorId: "senda", aircraft: "Phenom 300E", year: 2023, price: 7980, time: "1 h 05 min", eta: "Respuesta en 42 s", included: ["Catering ligero", "Wi-Fi", "Transfer en Ibiza"] },
  { id: "lacbleu", operatorId: "lacbleu", aircraft: "Praetor 600", year: 2022, price: 10400, time: "1 h 00 min", eta: "Respuesta en 1 min", included: ["Catering premium", "Azafata", "Flexibilidad ±2 h"] },
  { id: "aerocruz", operatorId: "aerocruz", aircraft: "Citation Latitude", year: 2021, price: 9250, time: "1 h 05 min", eta: "Respuesta en 2 min", included: ["Wi-Fi", "Mascota a bordo", "Bebidas premium"] },
];

export function QuoteFlow() {
  const [stage, setStage] = useState<Stage>("form"); const [shown, setShown] = useState(0); const [selected, setSelected] = useState(offers[0]); const [checkout, setCheckout] = useState(false);
  const [form, setForm] = useState<Form>({ from: "MAD", to: "IBZ", date: "2026-08-23", time: "17:30", trip: "one", passengers: 4, category: "light", extras: ["catering"] });
  useEffect(() => { const p = new URLSearchParams(window.location.search); setForm(current => ({...current, from:p.get("from")||current.from, to:p.get("to")||current.to, passengers:Number(p.get("pax"))||current.passengers})); }, []);
  useEffect(() => { if(stage !== "waiting") return; setShown(0); const timers = [700,1100,1500].map((delay,index)=>setTimeout(()=>{ setShown(index+1); if(index===2) setTimeout(()=>setStage("offers"),500); },delay)); return () => timers.forEach(clearTimeout); }, [stage]);
  const invalid = form.from === form.to || !form.date || form.passengers < 1;
  const set = <K extends keyof Form>(key: K, value: Form[K]) => setForm(current => ({...current,[key]:value}));
  const category = useMemo(()=>jetCategories.find(j=>j.id===form.category)!,[form.category]);

  if(stage === "detail") { const op=operators.find(o=>o.id===selected.operatorId)!; return <div className="container-blajet py-10 sm:py-16">
    <button onClick={()=>setStage("offers")} className="flex items-center gap-2 text-xs text-muted hover:text-champagne"><ArrowLeft size={15}/> Volver a las ofertas</button>
    <div className="mt-7 grid gap-8 lg:grid-cols-[1.25fr_.75fr]">
      <div><div className="grid gap-2 sm:grid-cols-[1.6fr_1fr]"><div className="relative min-h-72 sm:min-h-[430px]"><Image src={aircraftImage} alt={selected.aircraft} fill sizes="(max-width:1024px) 100vw, 60vw" className="object-cover"/></div><div className="relative hidden sm:block"><Image src={cabinImage} alt={`Cabina del ${selected.aircraft}`} fill sizes="25vw" className="object-cover"/></div></div>
        <div className="mt-8"><p className="eyebrow">Tu propuesta seleccionada</p><h1 className="display mt-4 text-5xl">{selected.aircraft} <span className="text-muted">· {selected.year}</span></h1><div className="mt-7 max-w-xl"><RouteVisual from={form.from} to={form.to}/></div></div>
        <div className="mt-10 grid gap-px bg-line sm:grid-cols-3"><div className="bg-canvas p-5"><Clock3 size={17} className="text-champagne"/><p className="mt-3 text-sm font-semibold">{selected.time}</p><p className="text-xs text-muted">Tiempo de vuelo</p></div><div className="bg-canvas p-5"><Plane size={17} className="text-champagne"/><p className="mt-3 text-sm font-semibold">{category.range}</p><p className="text-xs text-muted">Alcance de categoría</p></div><div className="bg-canvas p-5"><Luggage size={17} className="text-champagne"/><p className="mt-3 text-sm font-semibold">{category.luggage}</p><p className="text-xs text-muted">Capacidad</p></div></div>
      </div>
      <aside className="raised h-fit p-6 lg:sticky lg:top-24"><p className="eyebrow">Resumen</p><div className="mt-5 flex items-end justify-between"><span className="text-sm text-muted">Total estimado</span><span className="text-3xl font-semibold tabular">{selected.price.toLocaleString("es-ES")} <small className="text-xs font-normal text-muted">EUR</small></span></div><div className="mt-6 grid gap-3 border-y hairline py-5 text-xs"><p className="flex justify-between"><span className="text-muted">Vuelo y posicionamiento</span><span>{Math.round(selected.price*.86).toLocaleString("es-ES")} €</span></p><p className="flex justify-between"><span className="text-muted">Tasas y handling</span><span>{Math.round(selected.price*.09).toLocaleString("es-ES")} €</span></p><p className="flex justify-between"><span className="text-muted">Protección BlaJet</span><span>{Math.round(selected.price*.05).toLocaleString("es-ES")} €</span></p></div><p className="mt-5 flex gap-2 text-xs leading-5 text-muted"><ShieldCheck size={17} className="shrink-0 text-success"/> {op.name} · AOC {op.aoc} · {op.rating}/5</p><div className="mt-5 flex flex-wrap gap-2">{selected.included.map(i=><span key={i} className="border hairline px-2 py-1 text-[10px] text-muted">{i}</span>)}</div><button onClick={()=>setCheckout(true)} className="btn-primary mt-7 w-full">Reservar este jet</button><p className="mt-3 text-center text-[10px] text-muted">Sin cargos hasta la confirmación del operador.</p></aside>
    </div><BookingModal open={checkout} onClose={()=>setCheckout(false)} title={`${form.from} → ${form.to} · ${selected.aircraft}`} price={selected.price}/>
  </div> }

  if(stage === "waiting" || stage === "offers") return <div className="container-blajet py-12 sm:py-20"><div className="mx-auto max-w-5xl">
    <div className="text-center"><span className="mx-auto grid h-12 w-12 place-items-center border border-champagne text-champagne"><Plane size={22} strokeWidth={1.4}/></span><p className="eyebrow mt-6">Solicitud BJ-260823-184</p><h1 className="display mt-4 text-5xl">{stage === "waiting" ? "Los operadores están respondiendo." : "Tres propuestas. Una decisión sencilla."}</h1><p className="mx-auto mt-5 max-w-xl text-sm leading-6 text-muted">{form.from} → {form.to} · {form.date} · {form.passengers} viajeros. Comparamos aeronave, servicio y precio en el mismo formato.</p></div>
    <div className="mt-12 grid gap-4 lg:grid-cols-3">{offers.map((offer,index)=>{ const visible=index<shown || stage==="offers"; const op=operators.find(o=>o.id===offer.operatorId)!; return visible ? <article key={offer.id} className="raised animate-rise p-6" style={{animationDelay:`${index*80}ms`}}><div className="flex items-center justify-between"><span className="text-xs font-semibold">{op.name}</span>{index===0 && <span className="border border-success px-2 py-1 text-[9px] font-bold uppercase tracking-wider text-success">Mejor valor</span>}</div><h2 className="font-serif mt-7 text-2xl">{offer.aircraft}</h2><p className="mt-1 text-xs text-muted">{offer.year} · {offer.time} · {op.rating}/5</p><div className="mt-6 border-y hairline py-5"><span className="text-3xl font-semibold tabular">{offer.price.toLocaleString("es-ES")}</span> <small className="text-muted">EUR</small><p className="mt-1 text-[10px] text-muted">Precio total estimado</p></div><div className="mt-5 grid gap-2 text-xs text-muted">{offer.included.map(i=><p key={i} className="flex gap-2"><Check size={14} className="text-success"/>{i}</p>)}</div><button onClick={()=>{setSelected(offer);setStage("detail")}} className={index===0?"btn-primary mt-7 w-full":"btn-secondary mt-7 w-full"}>Ver propuesta <ArrowRight size={14}/></button></article> : <article key={offer.id} className="surface min-h-[410px] p-6"><div className="skeleton h-3 w-28"/><div className="skeleton mt-10 h-7 w-44"/><div className="skeleton mt-3 h-3 w-32"/><div className="skeleton mt-10 h-16 w-full"/><div className="skeleton mt-8 h-3 w-5/6"/><div className="skeleton mt-3 h-3 w-2/3"/></article>})}</div>
    {stage==="waiting" && <p className="mt-7 text-center text-xs text-muted">{shown === 0 ? "Enviando a 42 operadores verificados…" : `${shown} de 3 propuestas recibidas`}</p>}
    {stage==="offers" && <button onClick={()=>setStage("form")} className="mx-auto mt-8 flex items-center gap-2 text-xs text-muted hover:text-champagne"><ArrowLeft size={14}/> Modificar solicitud</button>}
  </div></div>;

  return <div className="container-blajet py-12 sm:py-20"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow">Charter a medida</p><h1 className="display mt-5 text-5xl sm:text-6xl">Tu jet. Tu horario. Tres ofertas comparables.</h1><p className="mt-6 max-w-md text-sm leading-7 text-muted">Cuéntanos dónde quieres estar. La red BlaJet responde y nosotros ordenamos cada detalle para que solo tengas que elegir.</p><div className="mt-9 hidden space-y-5 text-sm lg:block">{[["01","Define la ruta"],["02","Elige la cabina"],["03","Recibe tres propuestas"]].map(([n,t])=><p key={n} className="flex items-center gap-4"><span className="font-serif text-champagne">{n}</span>{t}</p>)}</div></div>
    <form onSubmit={(e)=>{e.preventDefault(); if(!invalid) setStage("waiting")}} className="raised p-5 sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><label><span className="field-label">Origen</span><select className="field" value={form.from} onChange={e=>set("from",e.target.value)}>{airports.map(([c,n])=><option key={c} value={c}>{c} · {n}</option>)}</select></label><label><span className="field-label">Destino</span><select className="field" value={form.to} onChange={e=>set("to",e.target.value)}>{airports.map(([c,n])=><option key={c} value={c}>{c} · {n}</option>)}</select>{form.from===form.to && <span className="mt-1 block text-xs text-alert">El destino debe ser distinto del origen.</span>}</label><label><span className="field-label">Fecha</span><input className="field" type="date" min="2026-08-10" value={form.date} onChange={e=>set("date",e.target.value)}/></label><label><span className="field-label">Hora preferida</span><input className="field" type="time" value={form.time} onChange={e=>set("time",e.target.value)}/></label><label><span className="field-label">Trayecto</span><select className="field" value={form.trip} onChange={e=>set("trip",e.target.value as Form["trip"])}><option value="one">Solo ida</option><option value="return">Ida y vuelta</option></select></label><label><span className="field-label">Viajeros</span><input className="field" type="number" min={1} max={16} value={form.passengers} onChange={e=>set("passengers",Number(e.target.value))}/></label></div>
      <fieldset className="mt-8"><legend className="field-label">Categoría de aeronave</legend><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{jetCategories.map(j=><button type="button" key={j.id} onClick={()=>set("category",j.id)} className={`p-4 text-left border ${form.category===j.id?"border-champagne bg-champagne/5":"hairline hover:border-champagne"}`}><span className="text-sm font-semibold">{j.name}</span><span className="mt-2 block text-[10px] leading-4 text-muted">{j.capacity} pax · {j.range}<br/>{j.speed} · {j.luggage}</span></button>)}</div></fieldset>
      <fieldset className="mt-8"><legend className="field-label">Extras opcionales</legend><div className="flex flex-wrap gap-2">{[["catering","Catering",Sparkles],["transfer","Transfer",Plane],["pet","Mascota",PawPrint],["wifi","Wi-Fi",Wifi],["hostess","Azafata",ShieldCheck]].map(([id,label,Icon])=>{const I=Icon as typeof Plane;const active=form.extras.includes(id as string);return <button type="button" key={id as string} onClick={()=>set("extras",active?form.extras.filter(x=>x!==id):[...form.extras,id as string])} className={`flex items-center gap-2 border px-3 py-2 text-xs ${active?"border-champagne text-champagne":"hairline text-muted"}`}><I size={14}/>{label as string}</button>})}</div></fieldset>
      <div className="mt-9 flex flex-col items-stretch justify-between gap-4 border-t hairline pt-6 sm:flex-row sm:items-center"><p className="text-xs leading-5 text-muted">Estimación de categoría: desde <strong className="text-ink tabular">{category.price.toLocaleString("es-ES")} €</strong><br/>Sin compromiso · respuesta media en 4 min</p><button disabled={invalid} className="btn-primary disabled:cursor-not-allowed disabled:opacity-40">Solicitar 3 ofertas <ArrowRight size={15}/></button></div>
    </form></div></div>;
}
